repos:
#    basic black check
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

#     pylint check
-   repo: https://github.com/pycqa/pylint
    rev: v3.3.0
    hooks:
    -   id: pylint

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1  # You can update this to the latest version
  hooks:
    - id: gitlint
      stages: [commit-msg]
      args:
        - --extra-line-rule
        - "T1^Commit message must start with 'DJ-' followed by 6 digits"
        - --ignore-by-default
        - "body"  # If you want to ignore other checks
        - --regex
        - "^DJ-[0-9]{6}"
